## The dataset is collected from the 1994 Census database and contains income data.
### Data Information:
* age: continuous.
* workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
* fnlwgt: continuous.
* education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
* education-num: continuous.
* marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
* occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
* relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
* race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
* sex: Female, Male.
* capital-gain: continuous.
* capital-loss: continuous.
* hours-per-week: continuous.
* native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
* salary: >50K, <=50K

## Conduct data analysis using Pandas by completing the specified tasks.

In [1]:
import pandas as pd

In [2]:
# Load the dataset
data = pd.read_csv("./data/adult.data.csv")
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. Count how many men and women (*sex* feature) are represented in this dataset.**

In [4]:
# your code
data.groupby("sex").size()

sex
Female    10771
Male      21790
dtype: int64

**2. What is the average age of men (*age* feature) across the entire dataset?**

In [5]:
# your code
data[data["sex"] == "Male"]["age"].agg("average")

np.float64(39.43354749885268)

**3. What is the proportion of United States citizens (*native-country* feature)?**

In [8]:
# your code
(data["native-country"] == "United-States").mean()

np.float64(0.895857006848684)

**4-5. Calculate the mean and standard deviation of age for those who earn more than 50K per year (*salary* feature) and those who earn less than 50K per year.**

In [14]:
# your code
data.groupby("salary")["age"].agg(["m"
"ean", "std"])

             mean        std
salary
<=50K   36.783738  14.020088
>50K    44.249841  10.519028

**6. Is it true that people who earn more than 50K have at least a higher education? (*education* feature – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters, or Doctorate)**

In [20]:
# your code
higher_education = ["Bachelors", "Prof-school", "Assoc-acdm", "Assoc-voc", "Masters","Doctorate"]

data[(data["salary"] == ">50K") & (~(data["education"]).isin(higher_education))]

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
38,31,Private,84154,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,38,?,>50K
55,43,Private,237993,Some-college,10,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32510,39,Private,107302,HS-grad,9,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,45,?,>50K
32518,57,Local-gov,110417,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,99999,0,40,United-States,>50K
32519,46,Private,364548,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,48,United-States,>50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

**7. Display age statistics for each race (*race* feature) and each sex. Use *groupby* and *describe*. Find the maximum age of men of the *Asian-Pac-Islander* race.**

In [23]:
# your code
data.groupby(["race", "sex"])["age"].describe()

                             count       mean        std   min   25%   50%  \
race               sex
Amer-Indian-Eskimo Female    119.0  37.117647  13.114991  17.0  27.0  36.0
                   Male      192.0  37.208333  12.049563  17.0  28.0  35.0
Asian-Pac-Islander Female    346.0  35.089595  12.300845  17.0  25.0  33.0
                   Male      693.0  39.073593  12.883944  18.0  29.0  37.0
Black              Female   1555.0  37.854019  12.637197  17.0  28.0  37.0
                   Male     1569.0  37.682600  12.882612  17.0  27.0  36.0
Other              Female    109.0  31.678899  11.631599  17.0  23.0  29.0
                   Male      162.0  34.654321  11.355531  17.0  26.0  32.0
White              Female   8642.0  36.811618  14.329093  17.0  25.0  35.0
                   Male    19174.0  39.652498  13.436029  17.0  29.0  38.0

                             75%   max
race               sex
Amer-Indian-Eskimo Female  46.00  80.0
                   Male    45.00  82.0
Asian-Pac-Islander Female  43.75  75.0
                   Male    46.00  90.0
Black              Female  46.00  90.0
                   Male    46.00  90.0
Other              Female  39.00  74.0
                   Male    42.00  77.0
White              Female  46.00  90.0
                   Male    49.00  90.0

**8. Among whom is there a higher proportion of high earners (>50K): married or single men (*marital-status* feature)? Consider those whose *marital-status* starts with *Married* (Married-civ-spouse, Married-spouse-absent, or Married-AF-spouse) as married, and the rest as single.**

In [37]:
# your code
import numpy as np

data["marital-status"] = np.where(data['marital-status'].str.startswith('Married'), "Married", "Single")

data[data["salary"] == ">50K"].groupby(["marital-status"]).size()

marital-status
Married    6736
Single     1105
dtype: int64

**9. What is the maximum number of hours a person works per week (*hours-per-week* feature)? How many people work this number of hours, and what is the percentage of high earners among them?**

In [48]:
# your code
max_hour = data["hours-per-week"].max()

data[data["hours-per-week"] == max_hour]["salary"].value_counts(normalize=True) * 100

salary
<=50K    70.588235
>50K     29.411765
Name: proportion, dtype: float64

**10. Calculate the average work time (*hours-per-week*) for low and high earners (*salary*) for each country (*native-country*).**

In [52]:
# your code
data.groupby(["native-country", "salary"])["hours-per-week"].agg("mean")

native-country  salary
?               <=50K     40.164760
                >50K      45.547945
Cambodia        <=50K     41.416667
                >50K      40.000000
Canada          <=50K     37.914634
                            ...
United-States   >50K      45.505369
Vietnam         <=50K     37.193548
                >50K      39.200000
Yugoslavia      <=50K     41.600000
                >50K      49.500000
Name: hours-per-week, Length: 82, dtype: float64

**11. Group people into age groups *young*, *adult*, *retiree*, where:**
* *young* corresponds to 16-35 years old
* *adult* - 35-70 years old
* *retiree* - 70-100 years old

**Assign the name of the corresponding group to each person in a new column called 'AgeGroup'.**

In [55]:
# your code
conditions = [
    (data['age'] >= 16) & (data['age'] < 35),
    (data['age'] >= 35) & (data['age'] < 70),
    (data['age'] >= 70) & (data['age'] <= 100)
]

choices = ['young', 'adult', 'retiree']

data['AgeGroup'] = np.select(conditions, choices, default=None)
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary,AgeGroup
0,39,State-gov,77516,Bachelors,13,Single,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,adult
1,50,Self-emp-not-inc,83311,Bachelors,13,Married,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,adult
2,38,Private,215646,HS-grad,9,Single,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,adult
3,53,Private,234721,11th,7,Married,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,adult
4,28,Private,338409,Bachelors,13,Married,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,young

**12-13. Determine the number of people earning >50K in each of the age groups (AgeGroup column), and also output the name of the age group that most frequently earns more than 50K (>50K).**

In [61]:
# your code
conditions = [
    (data['age'] >= 16) & (data['age'] < 35),
    (data['age'] >= 35) & (data['age'] < 70),
    (data['age'] >= 70) & (data['age'] <= 100)
]

choices = ['young', 'adult', 'retiree']

data['AgeGroup'] = np.select(conditions, choices, default=None)

data[data["salary"] == ">50K"].groupby("AgeGroup").size().reset_index(name="count").sort_values(by="count", ascending=False)

  AgeGroup  count
0    adult   6240
2    young   1488
1  retiree    113

**14. Group people by occupation (occupation column) and determine the number of people in each group. Then, write a filtering function *filter_func* that will return only those groups where the average age (age column) is no more than 40 and where all workers work more than 5 hours per week (hours-per-week column).**

In [70]:
# your code
def filter_func(group):
    return (group["age"].mean() <= 40) and (group["hours-per-week"].min() > 5)

result = (
    data.groupby("occupation")
    .filter(filter_func)
    .groupby("occupation")
    .size()
    .reset_index(name="count")
)
result

     occupation  count
0  Armed-Forces      9